### ISSUE TITLE
Change text size and font

### ISSUE THREAD

**Issue by Munchotaur** [jankammerath/gophie#12]
I would love to see a feature to change the text size and font (preferably from a choice of system fonts).

**Comment by jankammerath** [comment]
Would you want this for the content area (where the gopher content is display) only or for the entire user interface including the download window and the address bar?

**Comment by jankammerath** [comment]
The config.ini file already contains configuration for colours. Kindly let me know if this is sufficient for you.

**Comment by Munchotaur** [comment]
Really this would only need to be for the content area. A setting in config.ini for font size (and family if possible?) would be ideal.

Is there any way to expose this setting to the user (or have a `+` and `-` button in the bottom bar somewhere)?

**Comment by jankammerath** [comment]
Hi @Munchotaur 

I have added settings to the "Appearance" section of the config, so the Font and its size for the page view can be configured. Additionally also the size of the IconFont next to the text line is configurable.

```
[Appearance]
PAGE_FONT = Comic Sans MS
PAGE_FONT_SIZE = 15
PAGE_ICON_FONT_SIZE = 11
```

Kindly let me know if this does the job and I will close this issue.

**Comment by Munchotaur** [comment]
That works nicely -- thank you!
